// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ctrl.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ctrl_proto {

namespace {

const ::google::protobuf::Descriptor* CtrlRspRadioState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CtrlRspRadioState_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* CtrlCmd_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* CtrlStatus_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ctrl_2eproto() {
  protobuf_AddDesc_ctrl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ctrl.proto");
  GOOGLE_CHECK(file != NULL);
  CtrlRspRadioState_descriptor_ = file->message_type(0);
  static const int CtrlRspRadioState_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlRspRadioState, state_),
  };
  CtrlRspRadioState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CtrlRspRadioState_descriptor_,
      CtrlRspRadioState::default_instance_,
      CtrlRspRadioState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlRspRadioState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlRspRadioState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CtrlRspRadioState));
  CtrlCmd_descriptor_ = file->enum_type(0);
  CtrlStatus_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ctrl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CtrlRspRadioState_descriptor_, &CtrlRspRadioState::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ctrl_2eproto() {
  delete CtrlRspRadioState::default_instance_;
  delete CtrlRspRadioState_reflection_;
}

void protobuf_AddDesc_ctrl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ril_proto::protobuf_AddDesc_ril_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nctrl.proto\022\nctrl_proto\032\tril.proto\"9\n\021C"
    "trlRspRadioState\022$\n\005state\030\001 \002(\0162\025.ril_pr"
    "oto.RadioState*:\n\007CtrlCmd\022\021\n\rCTRL_CMD_EC"
    "HO\020\000\022\034\n\030CTRL_CMD_GET_RADIO_STATE\020\001*5\n\nCt"
    "rlStatus\022\022\n\016CTRL_STATUS_OK\020\000\022\023\n\017CTRL_STA"
    "TUS_ERR\020\001", 209);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ctrl.proto", &protobuf_RegisterTypes);
  CtrlRspRadioState::default_instance_ = new CtrlRspRadioState();
  CtrlRspRadioState::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ctrl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ctrl_2eproto {
  StaticDescriptorInitializer_ctrl_2eproto() {
    protobuf_AddDesc_ctrl_2eproto();
  }
} static_descriptor_initializer_ctrl_2eproto_;

const ::google::protobuf::EnumDescriptor* CtrlCmd_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CtrlCmd_descriptor_;
}
bool CtrlCmd_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CtrlStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CtrlStatus_descriptor_;
}
bool CtrlStatus_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int CtrlRspRadioState::kStateFieldNumber;
#endif  // !_MSC_VER

CtrlRspRadioState::CtrlRspRadioState()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CtrlRspRadioState::InitAsDefaultInstance() {
}

CtrlRspRadioState::CtrlRspRadioState(const CtrlRspRadioState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CtrlRspRadioState::SharedCtor() {
  _cached_size_ = 0;
  state_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CtrlRspRadioState::~CtrlRspRadioState() {
  SharedDtor();
}

void CtrlRspRadioState::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CtrlRspRadioState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CtrlRspRadioState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CtrlRspRadioState_descriptor_;
}

const CtrlRspRadioState& CtrlRspRadioState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ctrl_2eproto();  return *default_instance_;
}

CtrlRspRadioState* CtrlRspRadioState::default_instance_ = NULL;

CtrlRspRadioState* CtrlRspRadioState::New() const {
  return new CtrlRspRadioState;
}

void CtrlRspRadioState::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    state_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CtrlRspRadioState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ril_proto.RadioState state = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (ril_proto::RadioState_IsValid(value)) {
            set_state(static_cast< ril_proto::RadioState >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CtrlRspRadioState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ril_proto.RadioState state = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->state(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CtrlRspRadioState::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ril_proto.RadioState state = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->state(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CtrlRspRadioState::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ril_proto.RadioState state = 1;
    if (has_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CtrlRspRadioState::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CtrlRspRadioState* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CtrlRspRadioState*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CtrlRspRadioState::MergeFrom(const CtrlRspRadioState& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_state(from.state());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CtrlRspRadioState::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CtrlRspRadioState::CopyFrom(const CtrlRspRadioState& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CtrlRspRadioState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void CtrlRspRadioState::Swap(CtrlRspRadioState* other) {
  if (other != this) {
    std::swap(state_, other->state_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CtrlRspRadioState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CtrlRspRadioState_descriptor_;
  metadata.reflection = CtrlRspRadioState_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ctrl_proto

// @@protoc_insertion_point(global_scope)
